/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
exports.data = [
    "how do I calculate the mean of a collection?",
    "how I get the mean?",
    "how I get the mean of values in an array?",
    "how I get the absolute value of a number?",
    "how I get the sign of a variable?",
    "how to concatenate two strings?",
    "how to generate a random number?",
    "how to test if a value is odd?",
    "how to test if a set is empty?",
    "how to test if a string is lowercase?",
    "how to combine two dictionaries?",
    "how to generate a range?",
    "how to return the first item in a vector?",
    "how to return the largest item in a vector?",
    "how to merge two sets?",
    "how to combine two sets?",
    "how to reverse the characters of a string?",
    "how to reverse a string?",
    "how to get all the keys from a dictionary?",
    "how to get the horizontal concatenation of two arrays?",
    "how I get a square root?",
    "how to get the square root of a number?",
    "how to calculate the square root?",
    "how to get the median?",
    "how to calculate a median?",
    "how I get the median of a set?",
    "how to calculate the standard deviation?",
    "how to get a random number?",
    "how to get the convolution of two vectors?",
    "how I return the sign of a number?",
    "how to get the product of several numbers?",
    "how to calculate the convolution of two vectors?",
    "how I get a convolution?",
    "how I get the absolute value of the all the members of a collection?",
    "how to get the standard deviation?",
    "how I get the standard deviation of a vector of numbers?",
    "how to calculate an f.f.t.?",
    "how I get the fourier transform of an array?",
    "how to calculate a fast fourier transform?",
];
